import pandas as pd

# Paste your full multiline string here
raw_data = """
CASE_ID 
CASE_ID_status
FCUBS Ref No
CRL_APPLICANT ADDRESS_Value
CRL_APPLICANT ADDRESS_Value_status
APPLICANT ADDRESS1, APPLICANT ADDRESS2, APPLICANT ADDRESS3
CRL_APPLICANT COUNTRY_Value
CRL_APPLICANT COUNTRY_Value_status
APPLICANT COUNTRY
CRL_APPLICANT NAME_Value
CRL_APPLICANT NAME_Value_status
APPLICANT NAME
CRL_BENEFICIARY ACCOUNT NO / IBAN_Value
CRL_BENEFICIARY ACCOUNT NO / IBAN_Value_status
BENEFICIARY ACCOUNT NO / IBAN
CRL_BENEFICIARY ADDRESS_Value
CRL_BENEFICIARY ADDRESS_Value_status
BENEFICIARY ADDRESS1, BENEFICIARY ADDRESS2
CRL_BENEFICIARY BANK ADDRESS_Value
CRL_BENEFICIARY BANK ADDRESS_Value_status
BENEFICAIRY BANK ADDRESS1, BENEFICAIRY BANK ADDRESS2
CRL_BENEFICIARY BANK SWIFT CODE / SORT CODE/ BSB / IFS CODE_Value
CRL_BENEFICIARY BANK SWIFT CODE / SORT CODE/ BSB / IFS CODE_Value_status
BENEFICAIRY BANK SWIFT CODE / SORT CODE/ BSB / IFS CODE
CRL_BENEFICIARY BANK_Value
CRL_BENEFICIARY BANK_Value_status
BENEFICARY BANK
CRL_BENEFICIARY COUNTRY_Value
CRL_BENEFICIARY COUNTRY_Value_status
BENEFICIARY COUNTRY
CRL_BENEFICIARY NAME_Value
CRL_BENEFICIARY NAME_Value_status
BENEFICIARY NAME
CRL_CURRENCY AND AMOUNT OF REMITTANCE IN WORDS_Value
CRL_CURRENCY AND AMOUNT OF REMITTANCE IN WORDS_Value_status
REMITTANCE CURRENCY
CRL_CUSTOMER REQUEST LETTER DATE_Value
CRL_CUSTOMER REQUEST LETTER DATE_Value_status
CUSTOMER REQUEST LETTER DATE
CRL_DATE & TIME OF RECEIPT OF DOCUMENT_Value
CRL_DATE & TIME OF RECEIPT OF DOCUMENT_Value_status
DATE OF RECEIPT OF DOCUMENT
CRL_DEBIT ACCOUNT NO_Value
CRL_DEBIT ACCOUNT NO_Value_status
DEBIT ACCOUNT NO
CRL_DELIVERY PORT_Value
CRL_DELIVERY PORT_Value_status
SHIP TO PORT NAME
CRL_DESCRIPTION OF GOODS_Value
CRL_DESCRIPTION OF GOODS_Value_status
DESCRIPTION OF GOODS
CRL_DISPATCH PORT_Value
CRL_DISPATCH PORT_Value_status
Port of Discharge
CRL_FB CHARGES_Value
CRL_FB CHARGES_Value_status
FB CHARGES
CRL_FEE ACCOUNT NO_Value
CRL_FEE ACCOUNT NO_Value_status
FEE ACCOUNT NO
CRL_HS CODE_Value
CRL_HS CODE_Value_status
HSN CODE
CRL_IMPORT LICENSE DETAILS_Value
CRL_IMPORT LICENSE DETAILS_Value_status
LICENSE NUMBER
CRL_INCO TERM_Value
CRL_INCO TERM_Value_status
INCOTERM
CRL_INTERMEDIARY BANK ADDRESS_Value
CRL_INTERMEDIARY BANK ADDRESS_Value_status
INTERMEDIARY BANK ADDRESS1, INTERMEDIARY BANK ADDRESS2
CRL_INTERMEDIARY BANK COUNTRY_Value
CRL_INTERMEDIARY BANK COUNTRY_Value_status
INTERMEDIARY BANK COUNTRY
CRL_INTERMEDIARY BANK NAME_Value
CRL_INTERMEDIARY BANK NAME_Value_status
INTERMEDIARY BANK NAME
CRL_INVOICE DATE_Value
CRL_INVOICE DATE_Value_status
INVOICE Date
CRL_INVOICE NO_Value
CRL_INVOICE NO_Value_status
INVOICE Number
CRL_INVOICE VALUE_Value
CRL_INVOICE VALUE_Value_status
INVOICE Amount
CRL_LATEST SHIPMENT DATE_Value
CRL_LATEST SHIPMENT DATE_Value_status
LATEST SHIPMENT DATE
CRL_REMITTANCE AMOUNT_Value
CRL_REMITTANCE AMOUNT_Value_status
REMITTANCE AMOUNT
CRL_REMITTANCE CURRENCY_Value
CRL_REMITTANCE CURRENCY_Value_status
REMITTANCE CURRENCY
CRL_TYPE OF GOODS_Value
CRL_TYPE OF GOODS_Value_status
Type of Goods
INVOICE_BENEFICIARY ACCOUNT NO / IBAN_Value
INVOICE_BENEFICIARY ACCOUNT NO / IBAN_Value_status
BENEFICIARY ACCOUNT NO / IBAN-57
INVOICE_BENEFICIARY BANK ADDRESS_Value
INVOICE_BENEFICIARY BANK ADDRESS_Value_status
BENEFICAIRY BANK ADDRESS1, BENEFICAIRY BANK ADDRESS2
INVOICE_BENEFICIARY BANK SWIFT CODE / SORT CODE/ BSB / IFS CODE / ROUTING NO_Value
INVOICE_BENEFICIARY BANK SWIFT CODE / SORT CODE/ BSB / IFS CODE / ROUTING NO_Value_status
BENEFICAIRY BANK SWIFT CODE / SORT CODE/ BSB / IFS CODE
INVOICE_BENEFICIARY BANK_Value
INVOICE_BENEFICIARY BANK_Value_status
BENEFICARY BANK
INVOICE_BUYER ADDRESS_Value
INVOICE_BUYER ADDRESS_Value_status
APPLICANT ADDRESS1, APPLICANT ADDRESS2, APPLICANT ADDRESS3
INVOICE_BUYER COUNTRY_Value
INVOICE_BUYER COUNTRY_Value_status
APPLICANT COUNTRY
INVOICE_BUYER NAME_Value
INVOICE_BUYER NAME_Value_status
APPLICANT NAME
INVOICE_Beneficiary Address_Value
INVOICE_Beneficiary Address_Value_status
BENEFICIARY ADDRESS1, BENEFICIARY ADDRESS2
INVOICE_Beneficiary Name_Value
INVOICE_Beneficiary Name_Value_status
BENEFICIARY NAME
INVOICE_DESCRIPTION OF GOODS_Value
INVOICE_DESCRIPTION OF GOODS_Value_status
DESCRIPTION OF GOODS
INVOICE_HS CODE_Value
INVOICE_HS CODE_Value_status
HSN CODE
INVOICE_INCO TERM_Value
INVOICE_INCO TERM_Value_status
INCOTERM
INVOICE_INTERMEDIARY BANK ADDRESS_Value
INVOICE_INTERMEDIARY BANK ADDRESS_Value_status
INTERMEDIARY BANK ADDRESS1, INTERMEDIARY BANK ADDRESS2
INVOICE_INTERMEDIARY BANK COUNTRY_Value
INVOICE_INTERMEDIARY BANK COUNTRY_Value_status
INTERMEDIARY BANK COUNTRY
INVOICE_INTERMEDIARY BANK NAME_Value
INVOICE_INTERMEDIARY BANK NAME_Value_status
INTERMEDIARY BANK NAME
INVOICE_INVOICE AMOUNT/VALUE_Value
INVOICE_INVOICE AMOUNT/VALUE_Value_status
INVOICE Amount
INVOICE_INVOICE CURRENCY_Value
INVOICE_INVOICE CURRENCY_Value_status
INVOICE Currency
INVOICE_INVOICE DATE_Value
INVOICE_INVOICE DATE_Value_status
INVOICE Date
INVOICE_INVOICE NO_Value
INVOICE_INVOICE NO_Value_status
INVOICE Number
INVOICE_Invoice Amount_Value
INVOICE_Invoice Amount_Value_status
INVOICE Amount
INVOICE_MODE OF REMITTANCE_Value
INVOICE_MODE OF REMITTANCE_Value_status
REMITTANCE AMOUNT
INVOICE_PORT OF DISCHARGE_Value
INVOICE_PORT OF DISCHARGE_Value_status
Port of Discharge
INVOICE_PORT OF LOADING_Value
INVOICE_PORT OF LOADING_Value_status
Port of Loading
INVOICE_Party Country ( Beneficiary )_Value
INVOICE_Party Country ( Beneficiary )_Value_status
Beneficiary Country
INVOICE_Party Country ( Beneficiary Bank )_Value
INVOICE_Party Country ( Beneficiary Bank )_Value_status
Beneficiary Bank
INVOICE_Party Name ( Applicant )_Value
INVOICE_Party Name ( Applicant )_Value_status
Applicant Name
INVOICE_Party Name ( Beneficiary )_Value
INVOICE_Party Name ( Beneficiary )_Value_status
Beneficiary Name
INVOICE_Party Name ( Beneficiary Bank )_Value
INVOICE_Party Name ( Beneficiary Bank )_Value_status
Beneficiary Bank
INVOICE_Party Type ( Beneficiary Bank )_Value
INVOICE_Party Type ( Beneficiary Bank )_Value_status
Beneficiary Bank
INVOICE_Total INVOICE Amount_Value
INVOICE_Total INVOICE Amount_Value_status
INVOICE Amount
"""

# Clean and split lines
lines = [line.strip() for line in raw_data.strip().split('\n') if line.strip()]

# Split into 3 rows column-wise
rows = [[], [], []]
for i, line in enumerate(lines):
    rows[i % 3].append(line)

# Convert to DataFrame by transposing columns
df = pd.DataFrame(rows).transpose()

# Save to CSV
df.to_csv("columnwise_output.csv", index=False, header=False)

print("✅ CSV saved as 'columnwise_output.csv'")
